[tools]
zig = "0.15.2"

[tasks.build]
description = "build"
run = "zig build --summary all"

[tasks.test]
description = "test"
run = "zig build test --summary all"

[tasks.run]
description = "run"
run = "zig build run --summary all"

[tasks.bench]
description = "bench"
run = "zig build bench --summary all"

[tasks.e2e]
description = "e2e"
run = "zig build e2e --summary all"


