[tools]
zig = "0.16.0"
zls = "0.16.0"

[tasks.fmt]
description = "format"
run = "zig fmt src/"

[tasks."fmt-check"]
description = "format check"
run = "zig fmt --check src/"

[tasks.build]
description = "build"
run = "zig build --summary all"

[tasks.test]
description = "test"
run = "zig build test --summary all"

[tasks.example]
description = "example"
run = "zig build run --summary all"

[tasks.bench]
description = "bench"
run = "zig build bench --summary all"

[tasks.e2e]
description = "e2e"
run = "zig build e2e --summary all"
